### ISSUE TITLE
Is CUDA necessary or optional?

### ISSUE THREAD

**Issue by hanshammel1337** [krips89/opendetection#15]
Or otherwise asked: Do I need a dedicated Nvidia GPU to compile & work with Open Detection?

**Comment by lironsam** [comment]
For me, impossible for know to compile without Cuda... I need as well without Cuda as my MacBook Pro does not have GPU.

**Comment by shreyas29** [comment]
As per [Installation Instructions ](http://opendetection.com/installation_instruction.html)OpenCV CUDA module is required only if you want to use GPU enabled feature detectors and matcher.
