### ISSUE TITLE
trouble in building opendetection

### ISSUE THREAD

**Issue by anuj-rathore** [krips89/opendetection#19]
I tried building opendetection, but everytime it use to get stuck at 

**# **_include dir: include/od-1.0/od
include dir: share/doc/od-1.0/doxygen
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.11")_**** 

You can look here, to see how cmake goes:
http://pastebin.com/HH5vZxv3

**Comment by shyam671** [comment]
Hi anuj ,
I think first you need install openNI and may be openNI2 .

**Comment by anuj-rathore** [comment]
Resolved it, actually there was a problem in my data server!
