### ISSUE TITLE
Build errors in exmples

### ISSUE THREAD

**Issue by IshankGulati** [krips89/opendetection#3]
While building the examples in opendetection I got the following errors,
```
cp: cannot create regular file ‘/home/sarkar/libs/bin/’: No such file or directory
make[2]: *** [examples/apps/odcadrecog_test_single_model] Error 1
make[1]: *** [examples/apps/CMakeFiles/odcadrecog_test_single_model.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
I think it's due to a mistake [here]( https://github.com/krips89/opendetection/blob/master/examples/apps/CMakeLists.txt )
I am not sure but path should be either 
/usr/bin/
or 
/usr/libs/bin

**Comment by krips89** [comment]
I had built this app for personal use and hence the local path. I removed the post build command - it is not required as a part of the library.
